---
- name: Prepare machine
  hosts: all

  tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Create .env
      template:
        src: env.j2
        dest: /.env

- name: Init container
  hosts: all
  tasks:
    - name: Restart a container
      docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        ports:
          - "3000:3000"
        env_file: /.env
  roles:
    - { role: geerlingguy.pip }

- name: Monitoring
  hosts: webservers
  roles:
      - { role: datadog.datadog, become: yes }
