---
- name: Prepare machine
  hosts: all

  tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Create .env
      template:
        src: templates/env.j2
        dest: /.env

- name: Init container
  hosts: all
  tasks:
    - name: Asserts there is a running container matching the name and any provided configuration. Stopped and restarted.
      community.general.docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        ports:
          - "3000:3000"
        env_file: /.env
  vars:
    pip_install_packages:
      - name: docker
      - name: pip
  roles:
    - { role: geerlingguy.pip }

- name: Monitoring
  hosts: webservers
  roles:
      - { role: datadog.datadog, become: yes }
