---
- name: Prepare machine
  hosts: all

  tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Create .env
      template:
        src: env.j2
        dest: /.env

- name: Init container
  hosts: all
  tasks:
    - name: Restart a container
      docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        ports:
          - "3000:3000"
        env_file: /.env
  vars:
    pip_install_packages:
      - name: docker
      - name: pip
  roles:
    - { role: geerlingguy.pip }

- name: Monitoring
  hosts: webservers
  vars:
    datadog_api_key: "{{ VAULT_DATADOG_API_KEY }}"
    datadog_site: "datadoghq.com"
    datadog_checks:
      process:
        init_config:
        instances:
          - name: Instance 1
            url: 207.154.194.128:3000
          - name: Instance 2
            url: 159.89.6.143:3000
  roles:
      - { role: datadog.datadog, become: yes }
