---

datadog_api_key: "{{ VAULT_DATADOG_API_KEY }}"
datadog_site: "datadoghq.com"
datadog_checks:
  process:
    init_config:
    instances:
      - name: Load balancer
        url: 206.189.249.240

pip_install_packages:
  - name: docker
  - name: pip